CREATE TABLE IF NOT EXISTS trade_signals (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,
    side VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    bias VARCHAR(10) NOT NULL,
    strategy_version VARCHAR(20) NOT NULL,
    signal_time TIMESTAMP NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    stop_loss DOUBLE PRECISION NOT NULL,
    take_profit DOUBLE PRECISION NOT NULL,
    risk_reward DOUBLE PRECISION NOT NULL,
    signal_score INTEGER NOT NULL,
    reason TEXT NOT NULL,
    setup_json TEXT NOT NULL,
    close_time TIMESTAMP NULL,
    close_price DOUBLE PRECISION NULL,
    outcome VARCHAR(20) NULL,
    pnl_r DOUBLE PRECISION NULL,
    telegram_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_summaries (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    summary_date DATE NOT NULL UNIQUE,
    total_trades INTEGER NOT NULL,
    wins INTEGER NOT NULL,
    losses INTEGER NOT NULL,
    winrate DOUBLE PRECISION NOT NULL,
    total_r DOUBLE PRECISION NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS strategy_insights (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    trade_signal_id INTEGER UNIQUE,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    scope VARCHAR(30) NOT NULL,
    winrate DOUBLE PRECISION NOT NULL,
    total_trades INTEGER NOT NULL,
    recommendation TEXT NOT NULL
);
